elasticsearch:
  host: http://elasticsearch:9200
  timeout: 30
  log: false
  topic: message_query
redis:
  url: redis://redis:6379
token:
  expiration: 2.hours
whitelist:
  ip: 127.0.0.1, 0.0.0.0, localhost
db:
  host: localhost