version: "3"

volumes:
  es-volume:

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "7364:3306"
    volumes:
      - ./tmp/db:/tmp/mysql
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    networks:
      - backend
  backend:
    build: ./backend
    stdin_open: true
    tty: true
    ports:
      - "3333:3000"
    volumes:
      - .:/backend
    depends_on:
      - db
      - elasticsearch
    restart: always
    networks:
      - backend
  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend
  worker:
    build: ./backend
    volumes:
      - .:/backend
    depends_on:
      - db
      - redis
      - elasticsearch
    command: bundle exec sidekiq -C ./config/sidekiq.yml -e development -r .
    networks:
      - backend

networks:
  backend:
    driver: bridge